//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Dieser Quellcode wurde automatisch generiert von xsd, Version=4.6.1055.0.
// 
namespace Customer.Types.Schema.Samples.customerOrder {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://salesweb.customer.com/schemas/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="https://salesweb.customer.com/schemas/", IsNullable=false)]
    public partial class quantities {
        
        private quantityElementType immediatelyAvailableField;
        
        private quantityElementType itemField;
        
        private ItemChoiceType itemElementNameField;
        
        private quantityElementType delayedDeliveryField;
        
        private quantityElementType purchaseOrderField;
        
        private quantityElementType lackField;
        
        /// <remarks/>
        public quantityElementType immediatelyAvailable {
            get {
                return this.immediatelyAvailableField;
            }
            set {
                this.immediatelyAvailableField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("interBranchTransfer", typeof(quantityElementType))]
        [System.Xml.Serialization.XmlElementAttribute("interBranchTransferPossible", typeof(quantityElementType))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public quantityElementType Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
            }
        }
        
        /// <remarks/>
        public quantityElementType delayedDelivery {
            get {
                return this.delayedDeliveryField;
            }
            set {
                this.delayedDeliveryField = value;
            }
        }
        
        /// <remarks/>
        public quantityElementType purchaseOrder {
            get {
                return this.purchaseOrderField;
            }
            set {
                this.purchaseOrderField = value;
            }
        }
        
        /// <remarks/>
        public quantityElementType lack {
            get {
                return this.lackField;
            }
            set {
                this.lackField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://salesweb.customer.com/schemas/")]
    public partial class quantityElementType {
        
        private int valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://salesweb.customer.com/schemas/", IncludeInSchema=false)]
    public enum ItemChoiceType {
        
        /// <remarks/>
        interBranchTransfer,
        
        /// <remarks/>
        interBranchTransferPossible,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://salesweb.customer.com/schemas/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="https://salesweb.customer.com/schemas/", IsNullable=true)]
    public partial class client {
        
        private string numberField;
        
        private string passwordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://salesweb.customer.com/schemas/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="https://salesweb.customer.com/schemas/", IsNullable=true)]
    public partial class clientErrorResponse {
        
        private string numberField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://salesweb.customer.com/schemas/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="https://salesweb.customer.com/schemas/", IsNullable=true)]
    public partial class error {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://salesweb.customer.com/schemas/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="https://salesweb.customer.com/schemas/", IsNullable=true)]
    public partial class EAN {
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://salesweb.customer.com/schemas/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="https://salesweb.customer.com/schemas/", IsNullable=true)]
    public partial class pharmaCode {
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://salesweb.customer.com/schemas/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="https://salesweb.customer.com/schemas/", IsNullable=true)]
    public partial class supplierProductNumber {
        
        private string idField;
        
        private string eANsupplierIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        public string EANsupplierId {
            get {
                return this.eANsupplierIdField;
            }
            set {
                this.eANsupplierIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://salesweb.customer.com/schemas/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="https://salesweb.customer.com/schemas/", IsNullable=false)]
    public partial class deliveryAddress {
        
        private object itemField;
        
        private string line1Field;
        
        private string line4Field;
        
        private string line5PostalCodeField;
        
        private string line5CityField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("addressLine2And3BarCode", typeof(addressLine2And3BarCode), IsNullable=true)]
        [System.Xml.Serialization.XmlElementAttribute("addressLine2And3Text", typeof(addressLine2And3Text), IsNullable=true)]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string line1 {
            get {
                return this.line1Field;
            }
            set {
                this.line1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string line4 {
            get {
                return this.line4Field;
            }
            set {
                this.line4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string line5PostalCode {
            get {
                return this.line5PostalCodeField;
            }
            set {
                this.line5PostalCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string line5City {
            get {
                return this.line5CityField;
            }
            set {
                this.line5CityField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://salesweb.customer.com/schemas/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="https://salesweb.customer.com/schemas/", IsNullable=true)]
    public partial class addressLine2And3BarCode {
        
        private string barCode128Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string barCode128 {
            get {
                return this.barCode128Field;
            }
            set {
                this.barCode128Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://salesweb.customer.com/schemas/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="https://salesweb.customer.com/schemas/", IsNullable=true)]
    public partial class addressLine2And3Text {
        
        private string line2Field;
        
        private string line3Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string line2 {
            get {
                return this.line2Field;
            }
            set {
                this.line2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string line3 {
            get {
                return this.line3Field;
            }
            set {
                this.line3Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://salesweb.customer.com/schemas/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="https://salesweb.customer.com/schemas/", IsNullable=false)]
    public partial class orderDetails {
        
        private long pharmacyOrderNoField;
        
        private bool pharmacyOrderNoFieldSpecified;
        
        private long pharmacyCustomerNoField;
        
        private bool pharmacyCustomerNoFieldSpecified;
        
        private string pharmacyTourField;
        
        private string typeOfDispatchField;
        
        private long processIDField;
        
        private bool processIDFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long PharmacyOrderNo {
            get {
                return this.pharmacyOrderNoField;
            }
            set {
                this.pharmacyOrderNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PharmacyOrderNoSpecified {
            get {
                return this.pharmacyOrderNoFieldSpecified;
            }
            set {
                this.pharmacyOrderNoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long PharmacyCustomerNo {
            get {
                return this.pharmacyCustomerNoField;
            }
            set {
                this.pharmacyCustomerNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PharmacyCustomerNoSpecified {
            get {
                return this.pharmacyCustomerNoFieldSpecified;
            }
            set {
                this.pharmacyCustomerNoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PharmacyTour {
            get {
                return this.pharmacyTourField;
            }
            set {
                this.pharmacyTourField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TypeOfDispatch {
            get {
                return this.typeOfDispatchField;
            }
            set {
                this.typeOfDispatchField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long ProcessID {
            get {
                return this.processIDField;
            }
            set {
                this.processIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ProcessIDSpecified {
            get {
                return this.processIDFieldSpecified;
            }
            set {
                this.processIDFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://salesweb.customer.com/schemas/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="https://salesweb.customer.com/schemas/", IsNullable=false)]
    public partial class product {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("EAN", typeof(EAN), IsNullable=true)]
        [System.Xml.Serialization.XmlElementAttribute("pharmaCode", typeof(pharmaCode), IsNullable=true)]
        [System.Xml.Serialization.XmlElementAttribute("supplierProductNumber", typeof(supplierProductNumber), IsNullable=true)]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://salesweb.customer.com/schemas/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="https://salesweb.customer.com/schemas/", IsNullable=true)]
    public partial class productResponse {
        
        private quantities quantitiesField;
        
        private string wholesalerProductCodeField;
        
        private string descriptionField;
        
        private decimal basePiecePriceField;
        
        private decimal publicPricePerPieceField;
        
        private bool publicPricePerPieceFieldSpecified;
        
        private decimal baseLinePriceField;
        
        private decimal expectedLogisticServiceCostField;
        
        private string bonusQuantityField;
        
        private string invoiceQuantityField;
        
        private decimal discountPercentField;
        
        private bool discountPercentFieldSpecified;
        
        private string deliveryQuantityField;
        
        private bool campaignField;
        
        private float lineAmountField;
        
        private string migelCodeField;
        
        private string migelCodeDescriptionField;
        
        private string interbranchTransferQuantityField;
        
        /// <remarks/>
        public quantities quantities {
            get {
                return this.quantitiesField;
            }
            set {
                this.quantitiesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string wholesalerProductCode {
            get {
                return this.wholesalerProductCodeField;
            }
            set {
                this.wholesalerProductCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal basePiecePrice {
            get {
                return this.basePiecePriceField;
            }
            set {
                this.basePiecePriceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal publicPricePerPiece {
            get {
                return this.publicPricePerPieceField;
            }
            set {
                this.publicPricePerPieceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool publicPricePerPieceSpecified {
            get {
                return this.publicPricePerPieceFieldSpecified;
            }
            set {
                this.publicPricePerPieceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal baseLinePrice {
            get {
                return this.baseLinePriceField;
            }
            set {
                this.baseLinePriceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal expectedLogisticServiceCost {
            get {
                return this.expectedLogisticServiceCostField;
            }
            set {
                this.expectedLogisticServiceCostField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        public string bonusQuantity {
            get {
                return this.bonusQuantityField;
            }
            set {
                this.bonusQuantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        public string invoiceQuantity {
            get {
                return this.invoiceQuantityField;
            }
            set {
                this.invoiceQuantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal discountPercent {
            get {
                return this.discountPercentField;
            }
            set {
                this.discountPercentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool discountPercentSpecified {
            get {
                return this.discountPercentFieldSpecified;
            }
            set {
                this.discountPercentFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        public string deliveryQuantity {
            get {
                return this.deliveryQuantityField;
            }
            set {
                this.deliveryQuantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool campaign {
            get {
                return this.campaignField;
            }
            set {
                this.campaignField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float lineAmount {
            get {
                return this.lineAmountField;
            }
            set {
                this.lineAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string migelCode {
            get {
                return this.migelCodeField;
            }
            set {
                this.migelCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string migelCodeDescription {
            get {
                return this.migelCodeDescriptionField;
            }
            set {
                this.migelCodeDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        public string interbranchTransferQuantity {
            get {
                return this.interbranchTransferQuantityField;
            }
            set {
                this.interbranchTransferQuantityField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://salesweb.customer.com/schemas/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="https://salesweb.customer.com/schemas/", IsNullable=true)]
    public partial class productError {
        
        private string wholesalerProductCodeField;
        
        private string messageField;
        
        private string messageKeyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string wholesalerProductCode {
            get {
                return this.wholesalerProductCodeField;
            }
            set {
                this.wholesalerProductCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string messageKey {
            get {
                return this.messageKeyField;
            }
            set {
                this.messageKeyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://salesweb.customer.com/schemas/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="https://salesweb.customer.com/schemas/", IsNullable=true)]
    public partial class productMasterdata {
        
        private string wholesalerProductCodeField;
        
        private string descriptionField;
        
        private decimal basePiecePriceField;
        
        private decimal publicPricePerPieceField;
        
        private bool publicPricePerPieceFieldSpecified;
        
        private string migelCodeField;
        
        private string migelCodeDescriptionField;
        
        private string eANField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string wholesalerProductCode {
            get {
                return this.wholesalerProductCodeField;
            }
            set {
                this.wholesalerProductCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal basePiecePrice {
            get {
                return this.basePiecePriceField;
            }
            set {
                this.basePiecePriceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal publicPricePerPiece {
            get {
                return this.publicPricePerPieceField;
            }
            set {
                this.publicPricePerPieceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool publicPricePerPieceSpecified {
            get {
                return this.publicPricePerPieceFieldSpecified;
            }
            set {
                this.publicPricePerPieceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string migelCode {
            get {
                return this.migelCodeField;
            }
            set {
                this.migelCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string migelCodeDescription {
            get {
                return this.migelCodeDescriptionField;
            }
            set {
                this.migelCodeDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        public string EAN {
            get {
                return this.eANField;
            }
            set {
                this.eANField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://salesweb.customer.com/schemas/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="https://salesweb.customer.com/schemas/", IsNullable=false)]
    public partial class productConditionLevels {
        
        private productConditionLevel[] productConditionLevelField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("productConditionLevel")]
        public productConditionLevel[] productConditionLevel {
            get {
                return this.productConditionLevelField;
            }
            set {
                this.productConditionLevelField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://salesweb.customer.com/schemas/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="https://salesweb.customer.com/schemas/", IsNullable=false)]
    public partial class productConditionLevel {
        
        private productConditionType productConditionTypeField;
        
        private productConditionLevelPrice productConditionLevelPriceField;
        
        private System.DateTime validFromField;
        
        private bool validFromFieldSpecified;
        
        private System.DateTime validUntilField;
        
        private bool validUntilFieldSpecified;
        
        /// <remarks/>
        public productConditionType productConditionType {
            get {
                return this.productConditionTypeField;
            }
            set {
                this.productConditionTypeField = value;
            }
        }
        
        /// <remarks/>
        public productConditionLevelPrice productConditionLevelPrice {
            get {
                return this.productConditionLevelPriceField;
            }
            set {
                this.productConditionLevelPriceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
        public System.DateTime validFrom {
            get {
                return this.validFromField;
            }
            set {
                this.validFromField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool validFromSpecified {
            get {
                return this.validFromFieldSpecified;
            }
            set {
                this.validFromFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
        public System.DateTime validUntil {
            get {
                return this.validUntilField;
            }
            set {
                this.validUntilField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool validUntilSpecified {
            get {
                return this.validUntilFieldSpecified;
            }
            set {
                this.validUntilFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://salesweb.customer.com/schemas/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="https://salesweb.customer.com/schemas/", IsNullable=false)]
    public partial class productConditionType {
        
        private volumeDependentCondition volumeDependentConditionField;
        
        private string typeField;
        
        private string descriptionField;
        
        private bool isWholesalerFinancedField;
        
        private bool isSupplierFinancedField;
        
        private bool isManufacturerFinancedField;
        
        private bool is3rdPartyFinancedField;
        
        /// <remarks/>
        public volumeDependentCondition volumeDependentCondition {
            get {
                return this.volumeDependentConditionField;
            }
            set {
                this.volumeDependentConditionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool isWholesalerFinanced {
            get {
                return this.isWholesalerFinancedField;
            }
            set {
                this.isWholesalerFinancedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool isSupplierFinanced {
            get {
                return this.isSupplierFinancedField;
            }
            set {
                this.isSupplierFinancedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool isManufacturerFinanced {
            get {
                return this.isManufacturerFinancedField;
            }
            set {
                this.isManufacturerFinancedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool is3rdPartyFinanced {
            get {
                return this.is3rdPartyFinancedField;
            }
            set {
                this.is3rdPartyFinancedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://salesweb.customer.com/schemas/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="https://salesweb.customer.com/schemas/", IsNullable=false)]
    public partial class volumeDependentCondition {
        
        private decimal targetField;
        
        private decimal actualField;
        
        private targetDefinitionType targetDefinitionField;
        
        private decimal directDiscountPercentField;
        
        private int directDiscountMinimalQuantityField;
        
        private decimal targetAchievementDiscountPercentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal target {
            get {
                return this.targetField;
            }
            set {
                this.targetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal actual {
            get {
                return this.actualField;
            }
            set {
                this.actualField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public targetDefinitionType targetDefinition {
            get {
                return this.targetDefinitionField;
            }
            set {
                this.targetDefinitionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal directDiscountPercent {
            get {
                return this.directDiscountPercentField;
            }
            set {
                this.directDiscountPercentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int directDiscountMinimalQuantity {
            get {
                return this.directDiscountMinimalQuantityField;
            }
            set {
                this.directDiscountMinimalQuantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal targetAchievementDiscountPercent {
            get {
                return this.targetAchievementDiscountPercentField;
            }
            set {
                this.targetAchievementDiscountPercentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://salesweb.customer.com/schemas/")]
    public enum targetDefinitionType {
        
        /// <remarks/>
        turnover,
        
        /// <remarks/>
        quantity,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://salesweb.customer.com/schemas/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="https://salesweb.customer.com/schemas/", IsNullable=false)]
    public partial class productConditionLevelPrice {
        
        private string deliveryQuantityField;
        
        private string invoiceQuantityField;
        
        private string bonusQuantityField;
        
        private decimal discountPercentField;
        
        private bool discountPercentFieldSpecified;
        
        private decimal piecePriceField;
        
        private decimal expectedLogisticServiceCostField;
        
        private bool expectedLogisticServiceCostFieldSpecified;
        
        private decimal expectedTotalPiecePriceField;
        
        private bool expectedTotalPiecePriceFieldSpecified;
        
        private string contractQtyField;
        
        private string remainingQtyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        public string deliveryQuantity {
            get {
                return this.deliveryQuantityField;
            }
            set {
                this.deliveryQuantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        public string invoiceQuantity {
            get {
                return this.invoiceQuantityField;
            }
            set {
                this.invoiceQuantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        public string bonusQuantity {
            get {
                return this.bonusQuantityField;
            }
            set {
                this.bonusQuantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal discountPercent {
            get {
                return this.discountPercentField;
            }
            set {
                this.discountPercentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool discountPercentSpecified {
            get {
                return this.discountPercentFieldSpecified;
            }
            set {
                this.discountPercentFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal piecePrice {
            get {
                return this.piecePriceField;
            }
            set {
                this.piecePriceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal expectedLogisticServiceCost {
            get {
                return this.expectedLogisticServiceCostField;
            }
            set {
                this.expectedLogisticServiceCostField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool expectedLogisticServiceCostSpecified {
            get {
                return this.expectedLogisticServiceCostFieldSpecified;
            }
            set {
                this.expectedLogisticServiceCostFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal expectedTotalPiecePrice {
            get {
                return this.expectedTotalPiecePriceField;
            }
            set {
                this.expectedTotalPiecePriceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool expectedTotalPiecePriceSpecified {
            get {
                return this.expectedTotalPiecePriceFieldSpecified;
            }
            set {
                this.expectedTotalPiecePriceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        public string contractQty {
            get {
                return this.contractQtyField;
            }
            set {
                this.contractQtyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        public string remainingQty {
            get {
                return this.remainingQtyField;
            }
            set {
                this.remainingQtyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://salesweb.customer.com/schemas/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="https://salesweb.customer.com/schemas/", IsNullable=false)]
    public partial class productOrderLine {
        
        private object itemField;
        
        private string orderQuantityField;
        
        private bool roundUpForConditionField;
        
        private bool backLogDesiredField;
        
        private System.DateTime deliveryDateField;
        
        private bool deliveryDateFieldSpecified;
        
        public productOrderLine() {
            this.roundUpForConditionField = true;
            this.backLogDesiredField = true;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("EAN", typeof(EAN), IsNullable=true)]
        [System.Xml.Serialization.XmlElementAttribute("pharmaCode", typeof(pharmaCode), IsNullable=true)]
        [System.Xml.Serialization.XmlElementAttribute("supplierProductNumber", typeof(supplierProductNumber), IsNullable=true)]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        public string orderQuantity {
            get {
                return this.orderQuantityField;
            }
            set {
                this.orderQuantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool roundUpForCondition {
            get {
                return this.roundUpForConditionField;
            }
            set {
                this.roundUpForConditionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool backLogDesired {
            get {
                return this.backLogDesiredField;
            }
            set {
                this.backLogDesiredField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
        public System.DateTime deliveryDate {
            get {
                return this.deliveryDateField;
            }
            set {
                this.deliveryDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool deliveryDateSpecified {
            get {
                return this.deliveryDateFieldSpecified;
            }
            set {
                this.deliveryDateFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://salesweb.customer.com/schemas/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="https://salesweb.customer.com/schemas/", IsNullable=false)]
    public partial class productLabelOrderLine {
        
        private object itemField;
        
        private string defaultOrderQuantityField;
        
        private string orderTriggerQuantityField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("EAN", typeof(EAN), IsNullable=true)]
        [System.Xml.Serialization.XmlElementAttribute("pharmaCode", typeof(pharmaCode), IsNullable=true)]
        [System.Xml.Serialization.XmlElementAttribute("supplierProductNumber", typeof(supplierProductNumber), IsNullable=true)]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        public string defaultOrderQuantity {
            get {
                return this.defaultOrderQuantityField;
            }
            set {
                this.defaultOrderQuantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        public string orderTriggerQuantity {
            get {
                return this.orderTriggerQuantityField;
            }
            set {
                this.orderTriggerQuantityField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://salesweb.customer.com/schemas/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="https://salesweb.customer.com/schemas/", IsNullable=false)]
    public partial class browseRequest {
        
        private browseDirection directionField;
        
        private string requestKeyField;
        
        private string specificArticleCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public browseDirection direction {
            get {
                return this.directionField;
            }
            set {
                this.directionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string requestKey {
            get {
                return this.requestKeyField;
            }
            set {
                this.requestKeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        public string specificArticleCode {
            get {
                return this.specificArticleCodeField;
            }
            set {
                this.specificArticleCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://salesweb.customer.com/schemas/")]
    public enum browseDirection {
        
        /// <remarks/>
        next,
        
        /// <remarks/>
        previous,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://salesweb.customer.com/schemas/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="https://salesweb.customer.com/schemas/", IsNullable=false)]
    public partial class atFirst {
        
        private string nextPageKeyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string nextPageKey {
            get {
                return this.nextPageKeyField;
            }
            set {
                this.nextPageKeyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://salesweb.customer.com/schemas/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="https://salesweb.customer.com/schemas/", IsNullable=false)]
    public partial class atTheEnd {
        
        private string previousPageKeyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string previousPageKey {
            get {
                return this.previousPageKeyField;
            }
            set {
                this.previousPageKeyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://salesweb.customer.com/schemas/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="https://salesweb.customer.com/schemas/", IsNullable=false)]
    public partial class inBetween {
        
        private string nextPageKeyField;
        
        private string previousPageKeyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string nextPageKey {
            get {
                return this.nextPageKeyField;
            }
            set {
                this.nextPageKeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string previousPageKey {
            get {
                return this.previousPageKeyField;
            }
            set {
                this.previousPageKeyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://salesweb.customer.com/schemas/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="https://salesweb.customer.com/schemas/", IsNullable=true)]
    public partial class availability {
        
        private backlog backlogField;
        
        private availabilityType statusField;
        
        private string messageField;
        
        /// <remarks/>
        public backlog backlog {
            get {
                return this.backlogField;
            }
            set {
                this.backlogField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public availabilityType status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://salesweb.customer.com/schemas/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="https://salesweb.customer.com/schemas/", IsNullable=false)]
    public partial class backlog {
        
        private string quantityField;
        
        private backlogType backlogTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public backlogType backlogType {
            get {
                return this.backlogTypeField;
            }
            set {
                this.backlogTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://salesweb.customer.com/schemas/")]
    public enum backlogType {
        
        /// <remarks/>
        internalTransfer,
        
        /// <remarks/>
        externalDelivery,
        
        /// <remarks/>
        externalPurchase,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://salesweb.customer.com/schemas/")]
    public enum availabilityType {
        
        /// <remarks/>
        yes,
        
        /// <remarks/>
        YES,
        
        /// <remarks/>
        no,
        
        /// <remarks/>
        NO,
        
        /// <remarks/>
        later,
        
        /// <remarks/>
        LATER,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://salesweb.customer.com/schemas/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="https://salesweb.customer.com/schemas/", IsNullable=false)]
    public partial class customerOrder {
        
        private client clientField;
        
        private orderHeader orderHeaderField;
        
        private object[] orderLinesField;
        
        private decimal versionField;
        
        private int interfaceVersionField;
        
        private languageType languageField;
        
        private bool languageFieldSpecified;
        
        private bool roundUpForConditionField;
        
        private bool backLogDesiredField;
        
        private bool productDescriptionDesiredField;
        
        private bool compressionDesiredField;
        
        private string communicationSoftwareIdField;
        
        private bool interbranchTransferDetailsField;
        
        private bool tourDetailsField;
        
        public customerOrder() {
            this.versionField = ((decimal)(1.0m));
            this.interfaceVersionField = 1;
            this.roundUpForConditionField = true;
            this.backLogDesiredField = true;
            this.productDescriptionDesiredField = false;
            this.compressionDesiredField = false;
            this.interbranchTransferDetailsField = false;
            this.tourDetailsField = false;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public client client {
            get {
                return this.clientField;
            }
            set {
                this.clientField = value;
            }
        }
        
        /// <remarks/>
        public orderHeader orderHeader {
            get {
                return this.orderHeaderField;
            }
            set {
                this.orderHeaderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("productLabelOrderLine", typeof(productLabelOrderLine), IsNullable=false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("productOrderLine", typeof(productOrderLine), IsNullable=false)]
        public object[] orderLines {
            get {
                return this.orderLinesField;
            }
            set {
                this.orderLinesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(1)]
        public int interfaceVersion {
            get {
                return this.interfaceVersionField;
            }
            set {
                this.interfaceVersionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public languageType language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool languageSpecified {
            get {
                return this.languageFieldSpecified;
            }
            set {
                this.languageFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool roundUpForCondition {
            get {
                return this.roundUpForConditionField;
            }
            set {
                this.roundUpForConditionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool backLogDesired {
            get {
                return this.backLogDesiredField;
            }
            set {
                this.backLogDesiredField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool productDescriptionDesired {
            get {
                return this.productDescriptionDesiredField;
            }
            set {
                this.productDescriptionDesiredField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool compressionDesired {
            get {
                return this.compressionDesiredField;
            }
            set {
                this.compressionDesiredField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string communicationSoftwareId {
            get {
                return this.communicationSoftwareIdField;
            }
            set {
                this.communicationSoftwareIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool interbranchTransferDetails {
            get {
                return this.interbranchTransferDetailsField;
            }
            set {
                this.interbranchTransferDetailsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool tourDetails {
            get {
                return this.tourDetailsField;
            }
            set {
                this.tourDetailsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://salesweb.customer.com/schemas/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="https://salesweb.customer.com/schemas/", IsNullable=false)]
    public partial class orderHeader {
        
        private deliveryAddress deliveryAddressField;
        
        private orderDetails orderDetailsField;
        
        private System.DateTime deliveryDateField;
        
        private bool deliveryDateFieldSpecified;
        
        private string referenceNumberField;
        
        private bool urgentField;
        
        private bool phoneCallDesiredField;
        
        private bool phoneCallDesiredFieldSpecified;
        
        private mannerOfTransportType mannerOfTransportField;
        
        public orderHeader() {
            this.urgentField = false;
            this.mannerOfTransportField = mannerOfTransportType.tour;
        }
        
        /// <remarks/>
        public deliveryAddress deliveryAddress {
            get {
                return this.deliveryAddressField;
            }
            set {
                this.deliveryAddressField = value;
            }
        }
        
        /// <remarks/>
        public orderDetails orderDetails {
            get {
                return this.orderDetailsField;
            }
            set {
                this.orderDetailsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
        public System.DateTime deliveryDate {
            get {
                return this.deliveryDateField;
            }
            set {
                this.deliveryDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool deliveryDateSpecified {
            get {
                return this.deliveryDateFieldSpecified;
            }
            set {
                this.deliveryDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string referenceNumber {
            get {
                return this.referenceNumberField;
            }
            set {
                this.referenceNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool urgent {
            get {
                return this.urgentField;
            }
            set {
                this.urgentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool phoneCallDesired {
            get {
                return this.phoneCallDesiredField;
            }
            set {
                this.phoneCallDesiredField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool phoneCallDesiredSpecified {
            get {
                return this.phoneCallDesiredFieldSpecified;
            }
            set {
                this.phoneCallDesiredFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(mannerOfTransportType.tour)]
        public mannerOfTransportType mannerOfTransport {
            get {
                return this.mannerOfTransportField;
            }
            set {
                this.mannerOfTransportField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://salesweb.customer.com/schemas/")]
    public enum mannerOfTransportType {
        
        /// <remarks/>
        tour,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("post-express")]
        postexpress,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("self-pick-up")]
        selfpickup,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://salesweb.customer.com/schemas/")]
    public enum languageType {
        
        /// <remarks/>
        de,
        
        /// <remarks/>
        DE,
        
        /// <remarks/>
        fr,
        
        /// <remarks/>
        FR,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://salesweb.customer.com/schemas/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="https://salesweb.customer.com/schemas/", IsNullable=false)]
    public partial class orderLines {
        
        private object[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("productLabelOrderLine", typeof(productLabelOrderLine))]
        [System.Xml.Serialization.XmlElementAttribute("productOrderLine", typeof(productOrderLine))]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
}
